import type { GetServerSideProps, NextPage } from "next";
import Head from "next/head";
import type { Session } from "next-auth";
import { useSession } from "next-auth/react";
import TimeLine from "./components/TimeLine";
import Navbar from "./components/Navbar";
import { getSession } from "next-auth/react";
import React from "react";
import { parseFilterArgs } from "@tanstack/react-query";
import { type TimelineOptions } from "../utils/timelineOptions";

const Home: NextPage = () => {
  const { data: session } = useSession();
  if (!session) return null;

  const options: TimelineOptions = {
    filters: {
      author: {
        isNot: {
          id: session.user!.id,
        },
      },
    },
    sort: "asc",
    limit: 5,
  };

  return (
    <>
      <Head>
        <title>DeadEnd Devs</title>
        <meta name="description" content="Generated by Gabriel Pedroza" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div>
        <Navbar />
        <TimeLine options={options} />
      </div>
    </>
  );
};

export default Home;

export const getServerSideProps: GetServerSideProps = async (context) => {
  const session = await getSession(context);
  if (!session) {
    return {
      redirect: {
        destination: "/login",
        permanent: false,
      },
    };
  }

  return {
    props: {},
  };
};
