import { GetServerSideProps, type NextPage } from "next";
import Head from "next/head";
import TimeLine from "./components/TimeLine";
import Navbar from "./components/Navbar";
import { getSession } from "next-auth/react";

const Home: NextPage = () => {
  return (
    <>
      <Head>
        <title>DeadEnd Devs</title>
        <meta name="description" content="Generated by Gabriel Pedroza" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div>
        <Navbar />
        <TimeLine />
      </div>
    </>
  );
};

export default Home;

export const getServerSideProps: GetServerSideProps = async (context) => {
  const session = await getSession(context);
  if (!session) {
    return {
      redirect: {
        destination: "/login",
        permanent: false,
      },
    };
  }

  return {
    props: {
      // user: session?.user ? session?.user : null,
    },
  };
};