import { type NextPage } from "next";
import Head from "next/head";

import TimeLine from "./components/TimeLine";
import Navbar from "./components/Navbar";

const Home: NextPage = () => {
  return (
    <>
      <Head>
        <title>DeadEnd Devs</title>
        <meta name="description" content="Generated by Gabriel Pedroza" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div>
        <Navbar />
        <TimeLine />
      </div>
    </>
  );
};

export default Home;
